name = "now-playing"
main = "worker.js"
compatibility_date = "2025-09-01"
workers_dev = true
preview_urls = false

[vars]
LASTFM_USER = "luvrksnskyedev"
ALLOWED_ORIGINS = "https://luvrksknskyejourney.org,https://www.luvrksknskyejourney.org,http://127.0.0.1:5500,http://localhost:5500"
TIMEZONE = "America/Caracas"

[[ratelimits]]
name = "LIMITER"
namespace_id = "1001"

[ratelimits.simple]
limit = 60
period = 60

[[ratelimits]]
name = "WALL_LIMITER"
namespace_id = "1002"

[ratelimits.simple]
limit = 4
period = 60

[[d1_databases]]
binding = "DB"
database_name = "echo-wall"
database_id = "a2c2a19a-4e77-4fd3-ae29-2d8f2a079f3e"
migrations_dir = "migrations"
